// Package dom renders HTML as Go values. It is dreego's own DOM layer: a small,
// self-contained replacement for a template language. A normal dreego user only
// imports this package (and dreego), never a third-party HTML library.
//
// The core is deliberately tiny: View is anything that renders itself, and the
// HTML elements/attributes are mechanical one-liners (generated by
// internal/gen_dom). Because every attribute is just a node, higher-level
// attribute sets — like htmx's hx-* — fit in the same model without a special
// case.
package dom

import (
	"fmt"
	"html/template"
	"io"
	"strings"
)

// View is a value that can render itself as HTML into a writer. It is the one
// interface everything else is built on: elements, attributes, text, groups.
//
// A component is a function that returns a View, so a page reads top to bottom:
//
//	func Hero(c *dreego.Ctx) dreego.View { return d.Section(d.H1(d.Text("Hi"))) }
type View interface {
	Render(w io.Writer) error
}

// viewFunc is the common element node: a render function.
type viewFunc func(io.Writer) error

func (v viewFunc) Render(w io.Writer) error { return v(w) }

// String satisfies fmt.Stringer, so a View can be printed (and tested) directly.
func (v viewFunc) String() string {
	var b strings.Builder
	_ = v.Render(&b)
	return b.String()
}

// attrFunc is an attribute node: it renders into the opening tag, not the body.
type attrFunc func(io.Writer) error

func (a attrFunc) Render(w io.Writer) error { return a(w) }

func (a attrFunc) String() string {
	var b strings.Builder
	_ = a.Render(&b)
	return b.String()
}

// attribute marks a View as an attribute, so El renders it inside the tag.
type attribute interface {
	View
	isAttribute()
}

func (attrFunc) isAttribute() {}

// text is a plain, already-escaped text node.
type textNode string

func (t textNode) Render(w io.Writer) error { return writeString(w, string(t)) }
func (t textNode) String() string           { return string(t) }

// Group is a slice of Views that renders as one. Attributes directly inside a
// Group are ignored (they belong in an element), which mirrors HTML.
type Group []View

func (g Group) Render(w io.Writer) error {
	for _, kind := range g {
		if err := renderChild(w, kind, false); err != nil {
			return err
		}
	}
	return nil
}

func (g Group) String() string {
	var b strings.Builder
	_ = g.Render(&b)
	return b.String()
}

// El creates an element with a name and children. Children that are attributes
// render inside the opening tag; everything else renders as the body. Void
// elements (br, img, input, …) get no closing tag and no body.
func El(name string, children ...View) View {
	return viewFunc(func(w io.Writer) error {
		if err := writeString(w, "<"+name); err != nil {
			return err
		}
		for _, kind := range children {
			if err := renderChild(w, kind, true); err != nil {
				return err
			}
		}
		if err := writeString(w, ">"); err != nil {
			return err
		}
		if voidElements[name] {
			return nil
		}
		for _, kind := range children {
			if err := renderChild(w, kind, false); err != nil {
				return err
			}
		}
		return writeString(w, "</"+name+">")
	})
}

// renderChild renders a child. When onlyAttributes is true, only attribute nodes
// are rendered (used inside the opening tag); otherwise attributes are skipped.
func renderChild(w io.Writer, kind View, onlyAttributes bool) error {
	if kind == nil {
		return nil
	}
	if gruppe, istGruppe := kind.(Group); istGruppe {
		for _, inneres := range gruppe {
			if err := renderChild(w, inneres, onlyAttributes); err != nil {
				return err
			}
		}
		return nil
	}
	_, istAttribut := kind.(attribute)
	if onlyAttributes != istAttribut {
		return nil
	}
	return kind.Render(w)
}

// Attr creates an attribute: name-only (boolean) or name="value". More than one
// value panics — that is a programming error, not a runtime case.
func Attr(name string, value ...string) View {
	switch len(value) {
	case 0:
		return attrFunc(func(w io.Writer) error { return writeString(w, " "+name) })
	case 1:
		return attrFunc(func(w io.Writer) error {
			return writeString(w, " "+name+`="`+template.HTMLEscapeString(value[0])+`"`)
		})
	default:
		panic("dom.Attr: nur Name oder Name+Wert erlaubt")
	}
}

// Text creates an HTML-escaped text node.
func Text(s string) View { return textNode(template.HTMLEscapeString(s)) }

// Textf creates an HTML-escaped text node from a format string.
func Textf(format string, a ...any) View { return Text(fmt.Sprintf(format, a...)) }

// Raw creates an unescaped text node. Use only for trusted content.
func Raw(s string) View { return textNode(s) }

// Rawf creates an unescaped text node from a format string.
func Rawf(format string, a ...any) View { return Raw(fmt.Sprintf(format, a...)) }

// Map turns a slice into a Group by applying a function to each element.
func Map[T any](werte []T, f func(T) View) Group {
	knoten := make(Group, 0, len(werte))
	for _, wert := range werte {
		knoten = append(knoten, f(wert))
	}
	return knoten
}

// If returns the node when the condition is true, otherwise nil. Good for
// inlining elements conditionally.
func If(condition bool, kind View) View {
	if condition {
		return kind
	}
	return nil
}

// Iff calls f only when the condition is true (so the node is not built when it
// would be wasteful or would panic on nil data).
func Iff(condition bool, f func() View) View {
	if condition {
		return f()
	}
	return nil
}

// Doctype prefixes its sibling with "<!doctype html>".
func Doctype(sibling View) View {
	return viewFunc(func(w io.Writer) error {
		if err := writeString(w, "<!doctype html>"); err != nil {
			return err
		}
		return sibling.Render(w)
	})
}

// voidElements have no closing tag and no body.
// See https://html.spec.whatwg.org/multipage/syntax.html#void-elements
var voidElements = map[string]bool{
	"area": true, "base": true, "br": true, "col": true, "command": true,
	"embed": true, "hr": true, "img": true, "input": true, "keygen": true,
	"link": true, "meta": true, "param": true, "source": true, "track": true,
	"wbr": true,
}

// writeString writes s, preferring io.StringWriter when available.
func writeString(w io.Writer, s string) error {
	if sw, ok := w.(io.StringWriter); ok {
		_, err := sw.WriteString(s)
		return err
	}
	_, err := io.WriteString(w, s)
	return err
}
